config/routes.rb
Hsichanglin::Application.routes.draw do

  root :to => 'home#index'

  get '/contact' => 'home#contact'
  get '/about' => 'home#about'
  get '/resume' => 'home#resume'

  get '/etr' => 'home#etr'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def contact
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navbar.html.haml
.navbar
  .navbar_inner
    .group.half
      %span.nav-title
        Hsi-Chang Lin
    .group.half.nav-menu-item-container
      %span.nav-item
        = link_to 'Home', root_url
      %span.nav-item
        = link_to 'About', about_path
      %span.nav-item
        = link_to 'Resume', resume_path
      %span.nav-item
        = link_to 'Contact', contact_path
    .clear

app/views/home/about.html.haml
%h1
  About me.
  %p.about_subtitle_graph
    %span.grey.subtitle An unbiased, un-official auto-biography perpetually in progress.

.about_body
  %p.about_title_subheading
    After <span class="career_trigger" data-target="college">college</span>
    I
    <span class="career_trigger" data-target="music">wrote and performed music</span>,
    <span class="career_trigger" data-target="radio">produced public radio</span> and
    <span class="career_trigger" data-target="coding">developed software</span>.
  %p.about_title_subtitle
    \. . . I also took a swift stab at
    <span class="career_trigger" data-target="cooking">cooking professionally</span>.

.about_target_container
  #cube.cube-state-initial
    #main.face.open
      .about_main_image_left
      .about_main_image_right
      .clear

    #music.face
      .about_left_blank_black
        .about_music_overlay
          %p
            Between
            %span.large_print
              2000
            &amp;
            %span.large_print
              2005
            I was a member of the Newark, NJ based hip-hop crew dälek.

          %p
            While signed to Mike Patton's
            = link_to 'Ipecac', 'http://www.ipecac.com', :target => '_blank'
            record label, I released two
            = link_to 'critically', 'http://pitchfork.com/reviews/albums/2148-from-filthy-tongue-of-gods-and-griots/', :target => '_blank'

            = link_to 'acclaimed', 'http://pitchfork.com/reviews/albums/2149-absence/', :target => '_blank'
            LPs and a number of
            = link_to 'collaborative EPs', 'http://www.discogs.com/D%C3%A4lek-vs-Velma-D%C3%A4lek-Vs-Velma/release/1259196', :target => '_blank'
            with artists from around the world.

          %p
            We toured globally and we toured heavily, performing alongside many of my musical heroes; that said, our biggest honor and accomplishment had to be our collaboration with
            = link_to 'Faust', 'http://pitchfork.com/reviews/albums/3019-derbe-respect-alder-with-dalek/', :target => '_blank'
            &dash; the German musical pioneers who helped establish what is now known as the 'Krautrock' sound.

          %p
            In
            %span.large_print
              2005,
            I released
            = link_to 'Remains,', 'http://www.collide-scope.com/still-remains/', :target => '_blank'
            my solo album recorded using turntables and vinyl record sources to construct a haunting, atmospheric ambient score - a counterpoint to the heavy beats and aggressive sounds the band was known for.
      .about_music_image_right
      .clear

    #college.face
      .about_college_wide
        .about_college_wide_overlay
          %p
            From
            %span.large_print
              1997
            &dash;
            %span.large_print
              2001
            I attended
            %span.large_print
              Swarthmore College
            where I majored in Sociology and Anthropology and wrote a senior thesis titled 'Technology, Self &amp; Society.'

          %p
            My paper documented and analyzed an emerging musical lexicon among turntablists -- musicians who repurpose vinyl records and record players as their sole means of expression.

    #coding.face
      .about_coding_wide
      .about_coding_wide_overlay
        %p
          In late
          %span.large_print
            2012
          I enrolled in General Assembly's Web Development Immersive program where I studied several technologies including:

        %p.tech_cred_full_width
          %span.tech_cred_print
            Ruby

          %span.tech_cred_print
            Rails

          %span.tech_cred_print
            Javascript

          %span.tech_cred_print
            jQuery

          %span.tech_cred_print
            MySQL

          %span.tech_cred_print
            Postgres

          %span.tech_cred_print
            HTML5

          %span.tech_cred_print
            CSS3

          %span.tech_cred_print
            SASS

          %span.tech_cred_print
            HAML

          %span.tech_cred_print
            Git

          %span.tech_cred_print
            Heroku

          %span.tech_cred_print
            AWS

        %p
          In
          %span.large_print
            2013
          I became the 1st engineer hire at a start-up called
          = link_to 'Justworks', 'http://www.justworks.com', :target => '_blank'
          where I helped develop an automated payroll solution for small businesses.  Today, Justworks provides a one stop, self-serve platform that automatically manages a company's payroll, contractor payments, health benefits, 401k and more.

        %p.last
          I promise to use this site to showcase some personal projects on my
          = link_to 'Github,', 'http://www.github.com/hsichang', :target => '_blank'
          but until then you should feel free to look at my
          = link_to 'resume', resume_path
          for more information.

    #cooking.face
      .about_cooking_wide
        .about_cooking_half_overlay
          %p
            Anyone who knows me can attest to my passion for food.
          %p
            After reading Anthony Bordain's
            = link_to "'Kitchen Confidential'", 'http://www.amazon.com/Kitchen-Confidential-Anthony-Bourdain/dp/1408845040/ref=sr_1_3?s=books&ie=UTF8&qid=1404002819&sr=1-3&keywords=kitchen+confidential+by+anthony+bourdain', :target => '_blank'
            and
            = link_to "'Heat'", 'http://www.amazon.com/Heat-Adventures-Pasta-Maker-Apprentice-Dante-Quoting/dp/1400034477/ref=sr_1_1?s=books&ie=UTF8&qid=1404002756&sr=1-1&keywords=heat+bill+buford', :target => '_blank'
            by Bill Buford, I was inspired to take a stab at being a chef myself.
          %p
            From
            %span.large_print
              2006
            until
            %span.large_print
              2008
            &dash; under the tutelage of chef Daniel Parilla &dash; I was inducted into the super-intense, never-boring under-world of the professional kitchen by working my way up the line at
            = link_to '5Ninth,', 'http://nymag.com/nymetro/food/reviews/restaurant/9564/', :target => '_blank'
            a distinguished restaurant in New York City's Meatpacking District.

    #radio.face
      .about_radio_wide
        .about_radio_half_overlay
          %p
            I spent the years between
            %span.large_print
              2008
            &amp;
            %span.large_print
              2012
            working at
            = link_to 'WNYC / New York Public Radio.', 'http://www.wnyc.org', :target => '_blank'

          %p
            I got my foot in the door interning at
            = link_to 'RadioLab', 'http://www.radiolab.org', :target => '_blank'
            where I assisted in the production of its 5th season. Later, I would compose music for some of the show's live events.

          %p
            I held my first staff position at
            = link_to 'The Takeaway', 'http://www.thetakeaway.org', :target => '_blank'
            &dash; a nationally aired morning drive news program hosted by the inimitable
            = link_to 'John Hockenberry', 'http://en.wikipedia.org/wiki/John_Hockenberry', :target => '_blank'
            &dash; where I spent my days pitching news story ideas and interviewing political, academic and cultural figures of international renown in order to script and produce
            = link_to 'radio segments', 'http://www.thetakeaway.org/people/hsi-chang-lin/', :target => '_blank'
            for air the following morning.

          %p
            On the days that I filled in as the show's managing producer I was responsible for four hours of editorial content, organizing stories under tight deadlines.

          %p
            Along the way I filed stories for
            = link_to 'Studio 360,', 'http://www.studio360.org', :target => '_blank'
            and sat as judge on an American Idol-esque panel for the radio station's city-wide music competetion
            = link_to 'The Battle of the Borroughs', 'http://www.thegreenespace.org/series/battle-boroughs-2014/', :target => '_blank'
            on several occasions.

app/views/home/contact.html.haml
%h1
  Contact
.body
  %p
    I can be reached via email at
    = mail_to 'hsi.chang@gmail.com'
    or by phone at 347.986.7086.

app/views/home/etr.html.erb
<div class="page-container">
  <div class="left-container">
    <div class="elevator-btn-panel">
      <div class="row">
        <div class="floor-btn-container">
          <div class="floor-btn-display">1</div>
          <div class="floor-btn" data-btn="1">1</div>
          <div class="clear"></div>
        </div>
        <div class="floor-btn-container">
          <div class="floor-btn-display">2</div>
          <div class="floor-btn" data-btn="2">2</div>
          <div class="clear"></div>
        </div>
        <div class="clear"></div>
      </div>

      <div class="row">
        <div class="floor-btn-container">
          <div class="floor-btn-display">3</div>
          <div class="floor-btn" data-btn="3">3</div>
          <div class="clear"></div>
        </div>
        <div class="floor-btn-container">
          <div class="floor-btn-display">4</div>
          <div class="floor-btn" data-btn="4">4</div>
          <div class="clear"></div>
        </div>
        <div class="clear"></div>
      </div>

      <div class="row">
        <div class="floor-btn-container">
          <div class="floor-btn-display">5</div>
          <div class="floor-btn" data-btn="5">5</div>
          <div class="clear"></div>
        </div>
        <div class="floor-btn-container">
          <div class="floor-btn-display">6</div>
          <div class="floor-btn" data-btn="6">6</div>
          <div class="clear"></div>
        </div>
        <div class="clear"></div>
      </div>


      <div class="row">
        <div class="floor-btn-container">
          <div class="floor-btn-display">7</div>
          <div class="floor-btn" data-btn="7">7</div>
          <div class="clear"></div>
        </div>
        <div class="floor-btn-container">
          <div class="floor-btn-display">8</div>
          <div class="floor-btn" data-btn="8">8</div>
          <div class="clear"></div>
        </div>
        <div class="clear"></div>
      </div>


      <div class="row">
        <div class="floor-btn-container">
          <div class="floor-btn-display">9</div>
          <div class="floor-btn" data-btn="9">9</div>
          <div class="clear"></div>
        </div>
        <div class="floor-btn-container">
          <div class="floor-btn-display">10</div>
          <div class="floor-btn" data-btn="10">10</div>
          <div class="clear"></div>
        </div>
        <div class="clear"></div>
      </div>
    </div>
  </div>

  <div class="right-container">
    <div class="floor" data-floor="10">10</div>
    <div class="floor" data-floor="9">9</div>
    <div class="floor" data-floor="8">8</div>
    <div class="floor" data-floor="7">7</div>
    <div class="floor" data-floor="6">6</div>
    <div class="floor" data-floor="5">5</div>
    <div class="floor" data-floor="4">4</div>
    <div class="floor" data-floor="3">3</div>
    <div class="floor" data-floor="2">2</div>
    <div class="floor" data-floor="1">LOBBY</div>
  </div>

  <div class="clear"></div>
</div>

app/views/home/index.html.erb
<h1>Hello.</h1>

<div class="home_body">
  <p>
  I am an NYC based Front End Web Developer.
  </p>

  <p>
  At <a href="http://www.nowthisnews.com" target="_blank">NowThis</a>, my work is primarily focused on building cutting edge web applications using Node, Angular.js, React, Flux and HTML5.
  </p>
  <p>
  I am also a <a href="https://generalassemb.ly/instructors/hsi-chang-lin/3233" target="_blank">course instructor</a> at <a href="https://generalassemb.ly/" target="_blank">General Assembly</a>, where I teach the &quot;Programming for Non-Programmers&quot; bootcamps and workshops.
  </p>
</div>

app/views/home/index.html.haml
%h1
  Hello.

.home_body
  %p
    I am a Brooklyn, NY based Web Developer specializing in Ruby, Rails and Javascript.


/
  .dark_screen

  .container
    .cube.cube-animation
      .face.front
        %span.hello.hello-animation
          Hello
      .face.right
        %span.name
          My name is Hsi-Chang Lin
      .face.back
        %span.intro
          I am a web developer
      .face.left
        %span.tag
          This site is being updated now
      .face.bottom
        %span.me
          ME
      .face.top
        %span.skills
          I like: Ruby, Javascript, jQuery, MySQL, PostgreSQL, CSS3, HTML5 and more

app/views/home/index3d.html.haml
.dark_screen

.container
  .cube.cube-animation
    .face.front
      %span.hello.hello-animation
        Hello
    .face.right
      %span.name
        My name is Hsi-Chang Lin
    .face.back
      %span.intro
        I am a web developer
    .face.left
      %span.tag
        This site is being updated now
    .face.bottom
      %span.me
        ME
    .face.top
      %span.skills
        I like: Ruby, Javascript, jQuery, MySQL, PostgreSQL, CSS3, HTML5 and more

app/views/home/index_old.html.haml
%h1
  Hello.

.home_body
  %p
    I am a NYC based Front End Web Developer.  While I am trained in Ruby on Rails, my work these days is primarily focused on Angular.js, React, Flux and HTML5.

  %p
    I also teach


/
  .dark_screen

  .container
    .cube.cube-animation
      .face.front
        %span.hello.hello-animation
          Hello
      .face.right
        %span.name
          My name is Hsi-Chang Lin
      .face.back
        %span.intro
          I am a web developer
      .face.left
        %span.tag
          This site is being updated now
      .face.bottom
        %span.me
          ME
      .face.top
        %span.skills
          I like: Ruby, Javascript, jQuery, MySQL, PostgreSQL, CSS3, HTML5 and more

app/views/home/resume.html.haml
%h1
  Resume
.resume_body
  %p
    To download a .pdf copy of my resume click the link below.
.resume_link_container
  = link_to 'DOWNLOAD PDF', '/hsi_chang_lin_resume_2014.pdf', :class => 'button'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hsi-Chang Lin | Web Developer</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <script type="text/javascript" src="//use.typekit.net/rzw1ddv.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  </head>

  <body>
    <%= render 'navbar' %>

    <div class="site_container">

      <%= yield %>

      <footer>
        &copy; HCL2014
      </footer>

    </div>

  </body>

  <div id="footnotes_holder"></div>
</html>